[Interface]
Address = 10.24.0.1
ListenPort = 51820
PrivateKey = mOvnl5vc/CflJ7XUPpb27Jpy41S0Cv+PjaqNWe3n510=
PostUp = iptables -A FORWARD -i %i -o %i -p udp --dport 5353 -j ACCEPT; iptables -A FORWARD -i %i -o %i -p udp --dport 24240 -j ACCEPT; iptables -A FORWARD -i %i -o %i -p icmp -j ACCEPT; iptables -A FORWARD -i %i -o %i -j DROP; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.24.0.0/16 -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -o %i -p udp --dport 5353 -j ACCEPT; iptables -D FORWARD -i %i -o %i -p udp --dport 24240 -j ACCEPT; iptables -D FORWARD -i %i -o %i -p icmp -j ACCEPT; iptables -D FORWARD -i %i -o %i -j DROP; iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.24.0.0/16 -o eth+ -j MASQUERADE

