[Profile]
profile_id = forge

[Profile Detection]
os_id = 24hg-forge

[Anaconda]
product_name = 24HG Forge
product_url = https://os.24hgaming.com

[User Interface]
hidden_spokes =
custom_stylesheet = /usr/share/anaconda/pixmaps/forge-anaconda.css
