[Compositing]
AnimationSpeed=3
Backend=OpenGL
Enabled=true
HiddenPreviews=5
WindowsBlockCompositing=true

[Effect-overview]
BorderActivate=9

[Plugins]
blurEnabled=false
contrastEnabled=false
magiclampEnabled=false
slideEnabled=false
wobblywindowsEnabled=false

[Windows]
FocusPolicy=ClickToFocus
AutoRaise=false
AutoRaiseInterval=0
FocusStealingPreventionLevel=1
SeparateScreenFocus=false
BorderlessMaximizedWindows=true

[org.kde.kdecoration2]
ButtonsOnLeft=XIA
ButtonsOnRight=
library=org.kde.breeze
theme=Breeze

[TabBox]
DesktopLayout=org.kde.breeze.desktop
LayoutName=org.kde.breeze.desktop
