[Compositing]
AnimationSpeed=3
Backend=OpenGL
Enabled=true
GLCore=true
HiddenPreviews=5
OpenGLIsUnsafe=false
WindowsBlockCompositing=true

[Effect-overview]
BorderActivate=9

[Effect-magiclamp]
AnimationDuration=200

[Effect-translucency]
Inactive=90

[Plugins]
blurEnabled=true
contrastEnabled=true
magiclampEnabled=true
slideEnabled=false
wobblywindowsEnabled=false

[Windows]
FocusPolicy=ClickToFocus
AutoRaise=false
AutoRaiseInterval=0
FocusStealingPreventionLevel=1
SeparateScreenFocus=false
BorderlessMaximizedWindows=true

[org.kde.kdecoration2]
ButtonsOnLeft=XIA
ButtonsOnRight=
library=org.kde.breeze
theme=Breeze

[TabBox]
DesktopLayout=org.kde.breeze.desktop
LayoutName=org.kde.breeze.desktop
